CREATE TABLE IF NOT EXISTS external_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(100) NOT NULL,
    external_id VARCHAR(500) NOT NULL,
    source_notice_id VARCHAR(255) NOT NULL,
    title VARCHAR(2000) NOT NULL,
    published_date DATE,
    detail_url VARCHAR(4000),
    body CLOB,
    pia_related BOOLEAN NOT NULL,
    matched_keywords CLOB NOT NULL,
    classification_reason VARCHAR(4000) NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_external_notice_external_id UNIQUE (external_id)
);

CREATE TABLE IF NOT EXISTS external_notice_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_notice_id BIGINT NOT NULL,
    attachment_order INTEGER NOT NULL,
    file_name VARCHAR(2000),
    file_url VARCHAR(4000),
    CONSTRAINT fk_external_notice_attachment_notice
        FOREIGN KEY (external_notice_id) REFERENCES external_notice (id) ON DELETE CASCADE,
    CONSTRAINT uk_external_notice_attachment_order
        UNIQUE (external_notice_id, attachment_order)
);

CREATE TABLE IF NOT EXISTS notification_baseline (
    channel VARCHAR(50) NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    source_code VARCHAR(100) NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_notification_baseline
        PRIMARY KEY (channel, notification_type, source_code)
);

CREATE TABLE IF NOT EXISTS notification_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(50) NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    source_code VARCHAR(100) NOT NULL,
    external_id VARCHAR(500) NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    content_fingerprint CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    failure_reason VARCHAR(4000),
    CONSTRAINT uk_notification_delivery_dedup UNIQUE (
        channel, notification_type, source_code, external_id, content_fingerprint
    ),
    CONSTRAINT ck_notification_delivery_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS ix_notification_delivery_status_created
    ON notification_delivery (status, created_at);

CREATE TABLE IF NOT EXISTS notification_subscriber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    name VARCHAR(200),
    notification_type VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_subscriber_email_type
        UNIQUE (email, notification_type)
);

-- notification_delivery는 공지 변경 이벤트로 유지하고, 이 자식 테이블이 신청자별 발송 결과를 보관한다.
CREATE TABLE IF NOT EXISTS notification_subscriber_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_delivery_id BIGINT NOT NULL,
    subscriber_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    failure_reason VARCHAR(4000),
    CONSTRAINT fk_subscriber_delivery_notification
        FOREIGN KEY (notification_delivery_id) REFERENCES notification_delivery (id),
    CONSTRAINT fk_subscriber_delivery_subscriber
        FOREIGN KEY (subscriber_id) REFERENCES notification_subscriber (id),
    CONSTRAINT uk_subscriber_delivery_event_subscriber
        UNIQUE (notification_delivery_id, subscriber_id),
    CONSTRAINT ck_notification_subscriber_delivery_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS ix_subscriber_delivery_event_status
    ON notification_subscriber_delivery (notification_delivery_id, status);

-- 제출서류 수집 작업의 상태만 Biz Assist H2에 보관한다. 회사 DB의 사업 데이터는 snapshot으로만 참조한다.
CREATE TABLE IF NOT EXISTS submission_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT,
    project_public_id VARCHAR(36),
    project_code VARCHAR(255),
    internal_biz_no VARCHAR(255),
    project_name VARCHAR(2000) NOT NULL,
    bid_notice_no VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_submission_case_project UNIQUE (project_id),
    CONSTRAINT ck_submission_case_status CHECK (status IN ('DRAFT'))
);

-- 기존 파일 DB에도 수동 체크리스트 작업을 저장할 수 있도록 PMS snapshot 컬럼만 nullable로 완화한다.
ALTER TABLE submission_case ALTER COLUMN project_id DROP NOT NULL;
ALTER TABLE submission_case ALTER COLUMN project_public_id DROP NOT NULL;
ALTER TABLE submission_case ALTER COLUMN internal_biz_no DROP NOT NULL;

CREATE TABLE IF NOT EXISTS submission_document_requirement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_case_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    document_name VARCHAR(2000) NOT NULL,
    required BOOLEAN NOT NULL,
    evidence_text CLOB,
    source_type VARCHAR(50) NOT NULL,
    source_reference VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_submission_requirement_case
        FOREIGN KEY (submission_case_id) REFERENCES submission_case (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_submission_requirement_case
    ON submission_document_requirement (submission_case_id, id);

CREATE TABLE IF NOT EXISTS submission_document_selection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_case_id BIGINT NOT NULL,
    requirement_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    file_public_id VARCHAR(36) NOT NULL,
    original_filename VARCHAR(2000) NOT NULL,
    file_ext VARCHAR(100),
    file_modified_at TIMESTAMP,
    file_updated_at TIMESTAMP,
    selected_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_submission_selection_case
        FOREIGN KEY (submission_case_id) REFERENCES submission_case (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_selection_requirement
        FOREIGN KEY (requirement_id) REFERENCES submission_document_requirement (id) ON DELETE CASCADE,
    CONSTRAINT uk_submission_selection_requirement_file UNIQUE (requirement_id, file_id)
);

CREATE INDEX IF NOT EXISTS ix_submission_selection_case
    ON submission_document_selection (submission_case_id, requirement_id);

-- 회사 DB 파일을 복제하지 않고 공통 제출서류의 현재 사용본 reference와 갱신 정보만 보관한다.
CREATE TABLE IF NOT EXISTS submission_common_document (
    document_type VARCHAR(100) PRIMARY KEY,
    display_name VARCHAR(500) NOT NULL,
    file_id BIGINT,
    file_public_id VARCHAR(36),
    original_filename VARCHAR(2000),
    file_ext VARCHAR(100),
    issued_at DATE,
    expires_at DATE,
    refresh_policy VARCHAR(30) NOT NULL,
    refresh_interval_months INTEGER,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_common_document_refresh_policy
        CHECK (refresh_policy IN ('NONE', 'EXPIRATION_BASED', 'PERIODIC')),
    CONSTRAINT ck_common_document_periodic_interval
        CHECK ((refresh_policy = 'PERIODIC' AND refresh_interval_months > 0)
            OR (refresh_policy <> 'PERIODIC' AND refresh_interval_months IS NULL)),
    CONSTRAINT ck_common_document_file_reference
        CHECK ((file_id IS NULL AND file_public_id IS NULL AND original_filename IS NULL)
            OR (file_id IS NOT NULL AND file_public_id IS NOT NULL AND original_filename IS NOT NULL))
);

INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'BUSINESS_REGISTRATION', '사업자등록증', 'NONE', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'BUSINESS_REGISTRATION');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'BID_PARTICIPATION_REGISTRATION', '경쟁입찰참가자격등록증', 'NONE', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'BID_PARTICIPATION_REGISTRATION');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'CORPORATE_REGISTRY', '법인등기사항전부증명서', 'NONE', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'CORPORATE_REGISTRY');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'CORPORATE_SEAL_CERTIFICATE', '법인인감증명서', 'PERIODIC', 3, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'CORPORATE_SEAL_CERTIFICATE');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'PIA_INSTITUTION_CERTIFICATE', '개인정보 영향평가 기관 인증서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'PIA_INSTITUTION_CERTIFICATE');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'AUDIT_CORPORATION_REGISTRATION', '감리법인등록증', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'AUDIT_CORPORATION_REGISTRATION');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'SMALL_BUSINESS_CERTIFICATE', '중소기업확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'SMALL_BUSINESS_CERTIFICATE');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'WOMEN_OWNED_BUSINESS_CERTIFICATE', '여성기업확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'WOMEN_OWNED_BUSINESS_CERTIFICATE');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'STARTUP_BUSINESS_CERTIFICATE', '창업기업확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'STARTUP_BUSINESS_CERTIFICATE');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'CREDIT_RATING_CERTIFICATE', '신용평가등급확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'CREDIT_RATING_CERTIFICATE');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'SOFTWARE_BUSINESS_STATUS_CERTIFICATE', '소프트웨어사업자 일반현황 관리확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'SOFTWARE_BUSINESS_STATUS_CERTIFICATE');
INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
SELECT 'DIRECT_PRODUCTION_CERTIFICATE', '직접생산확인증명서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM submission_common_document WHERE document_type = 'DIRECT_PRODUCTION_CERTIFICATE');

-- 실적 수집 작업만 primary H2에 저장한다. 회사 DB/NAS에는 쓰지 않는다.
CREATE TABLE IF NOT EXISTS performance_project (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    deadline DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS performance_entry (
    id VARCHAR(36) PRIMARY KEY,
    project_id VARCHAR(36) NOT NULL REFERENCES performance_project(id),
    ppt_number VARCHAR(100) NOT NULL,
    business_name VARCHAR(1000) NOT NULL,
    business_period VARCHAR(500) NOT NULL,
    contract_amount VARCHAR(200) NOT NULL,
    client VARCHAR(500) NOT NULL,
    business_status VARCHAR(30),
    selected_file_id BIGINT,
    selected_filename VARCHAR(2000),
    selected_ext VARCHAR(100),
    evidence_type VARCHAR(30),
    kitc_status VARCHAR(30) NOT NULL,
    requested_at DATE,
    replied_at DATE,
    CONSTRAINT uk_performance_ppt_number UNIQUE(project_id, ppt_number),
    CONSTRAINT ck_performance_business_status CHECK(business_status IN ('COMPLETED', 'IN_PROGRESS')),
    CONSTRAINT ck_performance_evidence_type CHECK(evidence_type IN ('CERTIFICATE', 'CONTRACT')),
    CONSTRAINT ck_performance_kitc_status CHECK(kitc_status IN ('NEEDED', 'REQUESTED', 'RECEIVED')),
    CONSTRAINT ck_performance_file CHECK(
        (selected_file_id IS NULL AND selected_filename IS NULL AND selected_ext IS NULL AND evidence_type IS NULL)
        OR (selected_file_id IS NOT NULL AND selected_filename IS NOT NULL AND evidence_type IS NOT NULL)),
    CONSTRAINT ck_performance_kitc_dates CHECK(
        (kitc_status = 'NEEDED' AND requested_at IS NULL AND replied_at IS NULL)
        OR (kitc_status = 'REQUESTED' AND requested_at IS NOT NULL AND replied_at IS NULL)
        OR (kitc_status = 'RECEIVED' AND requested_at IS NOT NULL AND replied_at >= requested_at AND replied_at IS NOT NULL))
);

-- Private Drive references stay in primary H2. Existing company file selections are preserved.
CREATE TABLE IF NOT EXISTS performance_drive_file (
    id VARCHAR(36) PRIMARY KEY,
    origin VARCHAR(1000) NOT NULL,
    company VARCHAR(100) NOT NULL,
    drive_path VARCHAR(4000) NOT NULL,
    filename VARCHAR(2000) NOT NULL,
    file_ext VARCHAR(100),
    file_size BIGINT NOT NULL,
    modified_at TIMESTAMP,
    CONSTRAINT uk_performance_drive_locator UNIQUE(origin, company, drive_path)
);
ALTER TABLE performance_entry ADD COLUMN IF NOT EXISTS selected_drive_file_id VARCHAR(36)
    REFERENCES performance_drive_file(id);
ALTER TABLE performance_entry DROP CONSTRAINT IF EXISTS ck_performance_file;
ALTER TABLE performance_entry ADD CONSTRAINT ck_performance_file CHECK(
    (selected_file_id IS NULL AND selected_drive_file_id IS NULL
        AND selected_filename IS NULL AND selected_ext IS NULL AND evidence_type IS NULL)
    OR (((selected_file_id IS NOT NULL AND selected_drive_file_id IS NULL)
        OR (selected_file_id IS NULL AND selected_drive_file_id IS NOT NULL))
        AND selected_filename IS NOT NULL AND evidence_type IS NOT NULL)
);
CREATE TABLE IF NOT EXISTS drive_file_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(1000) NOT NULL,
    company VARCHAR(100) NOT NULL,
    root VARCHAR(4000) NOT NULL,
    name VARCHAR(2000) NOT NULL,
    path VARCHAR(4000) NOT NULL,
    ext VARCHAR(100),
    size BIGINT NOT NULL,
    last_modified TIMESTAMP WITH TIME ZONE,
    indexed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_drive_index_locator UNIQUE(source, company, root, path)
);
CREATE TABLE IF NOT EXISTS drive_index_root_state (
    source VARCHAR(1000) NOT NULL,
    company VARCHAR(100) NOT NULL,
    root VARCHAR(4000) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('REFRESHING', 'SUCCESS', 'FAILED')),
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    last_success_at TIMESTAMP WITH TIME ZONE,
    folder_count BIGINT NOT NULL DEFAULT 0,
    file_count BIGINT NOT NULL DEFAULT 0,
    error_code VARCHAR(100),
    PRIMARY KEY(source, company, root)
);
-- Local submission projects reuse submission_case.id; project_id remains the PMS identifier.
ALTER TABLE submission_case ADD COLUMN IF NOT EXISTS organization_name VARCHAR(2000);
ALTER TABLE submission_case ADD COLUMN IF NOT EXISTS performance_project_id VARCHAR(36)
    REFERENCES performance_project(id);
ALTER TABLE submission_case ADD COLUMN IF NOT EXISTS performance_link_initialized BOOLEAN NOT NULL DEFAULT FALSE;
-- Existing projects retain an unset deadline until edited; new project API requires it.
ALTER TABLE submission_case ADD COLUMN IF NOT EXISTS deadline DATE;
-- Independent catalog; no FK from project requirements or selections.
CREATE TABLE IF NOT EXISTS submission_document_master (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(32) NOT NULL CHECK (category IN ('COMPANY_COMMON','PERSONNEL','PERFORMANCE','OTHER')),
    requirement_category VARCHAR(32) NOT NULL,
    source_reference VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1000,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'BUSINESS_REGISTRATION','사업자등록증','COMPANY_COMMON','COMPANY_GENERAL','BUSINESS_REGISTRATION',0 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='BUSINESS_REGISTRATION');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'BID_PARTICIPATION_REGISTRATION','경쟁입찰참가자격등록증','COMPANY_COMMON','COMPANY_GENERAL','BID_PARTICIPATION_REGISTRATION',1 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='BID_PARTICIPATION_REGISTRATION');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'CORPORATE_REGISTRY','법인등기사항전부증명서','COMPANY_COMMON','COMPANY_GENERAL','CORPORATE_REGISTRY',2 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='CORPORATE_REGISTRY');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'CORPORATE_SEAL_CERTIFICATE','법인인감증명서','COMPANY_COMMON','COMPANY_GENERAL','CORPORATE_SEAL_CERTIFICATE',3 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='CORPORATE_SEAL_CERTIFICATE');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'PIA_INSTITUTION_CERTIFICATE','개인정보 영향평가 기관 인증서','COMPANY_COMMON','CERTIFICATION_LICENSE','PIA_INSTITUTION_CERTIFICATE',4 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='PIA_INSTITUTION_CERTIFICATE');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'AUDIT_CORPORATION_REGISTRATION','감리법인등록증','COMPANY_COMMON','CERTIFICATION_LICENSE','AUDIT_CORPORATION_REGISTRATION',5 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='AUDIT_CORPORATION_REGISTRATION');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'SMALL_BUSINESS_CERTIFICATE','중소기업확인서','COMPANY_COMMON','CERTIFICATION_LICENSE','SMALL_BUSINESS_CERTIFICATE',6 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='SMALL_BUSINESS_CERTIFICATE');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'WOMEN_OWNED_BUSINESS_CERTIFICATE','여성기업확인서','COMPANY_COMMON','CERTIFICATION_LICENSE','WOMEN_OWNED_BUSINESS_CERTIFICATE',7 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='WOMEN_OWNED_BUSINESS_CERTIFICATE');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'STARTUP_BUSINESS_CERTIFICATE','창업기업확인서','COMPANY_COMMON','CERTIFICATION_LICENSE','STARTUP_BUSINESS_CERTIFICATE',8 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='STARTUP_BUSINESS_CERTIFICATE');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'CREDIT_RATING_CERTIFICATE','신용평가등급확인서','COMPANY_COMMON','FINANCIAL','CREDIT_RATING_CERTIFICATE',9 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='CREDIT_RATING_CERTIFICATE');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'SOFTWARE_BUSINESS_STATUS_CERTIFICATE','소프트웨어사업자 일반현황 관리확인서','COMPANY_COMMON','CERTIFICATION_LICENSE','SOFTWARE_BUSINESS_STATUS_CERTIFICATE',10 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='SOFTWARE_BUSINESS_STATUS_CERTIFICATE');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'DIRECT_PRODUCTION_CERTIFICATE','직접생산확인증명서','COMPANY_COMMON','CERTIFICATION_LICENSE','DIRECT_PRODUCTION_CERTIFICATE',11 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='DIRECT_PRODUCTION_CERTIFICATE');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'EMPLOYMENT','재직증명서','PERSONNEL','PERSONNEL','EMPLOYMENT',12 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='EMPLOYMENT');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'QUALIFICATION','자격증','PERSONNEL','CERTIFICATION_LICENSE','QUALIFICATION',13 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='QUALIFICATION');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'KOSA_CAREER','KOSA 경력증명서','PERSONNEL','PERSONNEL','KOSA_CAREER',14 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='KOSA_CAREER');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'GRADUATION','졸업증명서','PERSONNEL','PERSONNEL','GRADUATION',15 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='GRADUATION');
INSERT INTO submission_document_master(id,name,category,requirement_category,source_reference,sort_order) SELECT 'PERFORMANCE','실적증명서','PERFORMANCE','PERFORMANCE','PERFORMANCE',16 WHERE NOT EXISTS (SELECT 1 FROM submission_document_master WHERE id='PERFORMANCE');

-- Biz Assist-owned uploads: UUID references are independent of company file IDs.
CREATE TABLE IF NOT EXISTS submission_uploaded_file (
    id VARCHAR(36) PRIMARY KEY,
    original_filename VARCHAR(2000) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE submission_common_document ADD COLUMN IF NOT EXISTS uploaded_file_id VARCHAR(36) REFERENCES submission_uploaded_file(id);
ALTER TABLE submission_document_selection ALTER COLUMN file_id DROP NOT NULL;
ALTER TABLE submission_document_selection ALTER COLUMN file_public_id DROP NOT NULL;
ALTER TABLE submission_document_selection ADD COLUMN IF NOT EXISTS uploaded_file_id VARCHAR(36) REFERENCES submission_uploaded_file(id);

ALTER TABLE submission_common_document DROP CONSTRAINT IF EXISTS ck_common_document_file_reference;
ALTER TABLE submission_common_document ADD CONSTRAINT IF NOT EXISTS ck_common_document_current_reference CHECK (
    (uploaded_file_id IS NOT NULL AND file_id IS NULL AND file_public_id IS NULL AND original_filename IS NOT NULL)
    OR (uploaded_file_id IS NULL AND ((file_id IS NULL AND file_public_id IS NULL AND original_filename IS NULL)
        OR (file_id IS NOT NULL AND file_public_id IS NOT NULL AND original_filename IS NOT NULL)))
);
ALTER TABLE submission_document_selection ADD CONSTRAINT IF NOT EXISTS ck_submission_selection_source CHECK (
    (uploaded_file_id IS NOT NULL AND file_id IS NULL AND file_public_id IS NULL)
    OR (uploaded_file_id IS NULL AND file_id IS NOT NULL AND file_public_id IS NOT NULL)
);
