CREATE TABLE IF NOT EXISTS external_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(100) NOT NULL,
    external_id VARCHAR(500) NOT NULL,
    source_notice_id VARCHAR(255) NOT NULL,
    title VARCHAR(2000) NOT NULL,
    published_date DATE,
    detail_url VARCHAR(4000),
    body CLOB,
    pia_related BOOLEAN NOT NULL,
    matched_keywords CLOB NOT NULL,
    classification_reason VARCHAR(4000) NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_external_notice_external_id UNIQUE (external_id)
);

CREATE TABLE IF NOT EXISTS external_notice_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_notice_id BIGINT NOT NULL,
    attachment_order INTEGER NOT NULL,
    file_name VARCHAR(2000),
    file_url VARCHAR(4000),
    CONSTRAINT fk_external_notice_attachment_notice
        FOREIGN KEY (external_notice_id) REFERENCES external_notice (id) ON DELETE CASCADE,
    CONSTRAINT uk_external_notice_attachment_order
        UNIQUE (external_notice_id, attachment_order)
);

CREATE TABLE IF NOT EXISTS notification_baseline (
    channel VARCHAR(50) NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    source_code VARCHAR(100) NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_notification_baseline
        PRIMARY KEY (channel, notification_type, source_code)
);

CREATE TABLE IF NOT EXISTS notification_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(50) NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    source_code VARCHAR(100) NOT NULL,
    external_id VARCHAR(500) NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    content_fingerprint CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    failure_reason VARCHAR(4000),
    CONSTRAINT uk_notification_delivery_dedup UNIQUE (
        channel, notification_type, source_code, external_id, content_fingerprint
    ),
    CONSTRAINT ck_notification_delivery_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS ix_notification_delivery_status_created
    ON notification_delivery (status, created_at);

CREATE TABLE IF NOT EXISTS notification_subscriber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    name VARCHAR(200),
    notification_type VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_subscriber_email_type
        UNIQUE (email, notification_type)
);

-- notification_delivery는 공지 변경 이벤트로 유지하고, 이 자식 테이블이 신청자별 발송 결과를 보관한다.
CREATE TABLE IF NOT EXISTS notification_subscriber_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_delivery_id BIGINT NOT NULL,
    subscriber_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    failure_reason VARCHAR(4000),
    CONSTRAINT fk_subscriber_delivery_notification
        FOREIGN KEY (notification_delivery_id) REFERENCES notification_delivery (id),
    CONSTRAINT fk_subscriber_delivery_subscriber
        FOREIGN KEY (subscriber_id) REFERENCES notification_subscriber (id),
    CONSTRAINT uk_subscriber_delivery_event_subscriber
        UNIQUE (notification_delivery_id, subscriber_id),
    CONSTRAINT ck_notification_subscriber_delivery_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS ix_subscriber_delivery_event_status
    ON notification_subscriber_delivery (notification_delivery_id, status);
