-- Biz Assist PostgreSQL baseline. This is the final schema for a new, empty database.
-- Existing H2 databases continue to use schema.sql through the h2 profile.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE external_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(100) NOT NULL,
    external_id VARCHAR(500) NOT NULL,
    source_notice_id VARCHAR(255) NOT NULL,
    title VARCHAR(2000) NOT NULL,
    published_date DATE,
    detail_url VARCHAR(4000),
    body TEXT,
    pia_related BOOLEAN NOT NULL,
    matched_keywords TEXT NOT NULL,
    classification_reason VARCHAR(4000) NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_external_notice_external_id UNIQUE (external_id)
);

CREATE TABLE external_notice_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_notice_id BIGINT NOT NULL,
    attachment_order INTEGER NOT NULL,
    file_name VARCHAR(2000),
    file_url VARCHAR(4000),
    CONSTRAINT fk_external_notice_attachment_notice
        FOREIGN KEY (external_notice_id) REFERENCES external_notice (id) ON DELETE CASCADE,
    CONSTRAINT uk_external_notice_attachment_order
        UNIQUE (external_notice_id, attachment_order)
);

CREATE TABLE bid_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(50) NOT NULL,
    source_notice_id VARCHAR(500) NOT NULL,
    revision_key VARCHAR(255) NOT NULL DEFAULT '',
    notice_number VARCHAR(255),
    title VARCHAR(2000) NOT NULL,
    ordering_organization VARCHAR(1000),
    published_at TIMESTAMP WITHOUT TIME ZONE,
    submission_deadline_at TIMESTAMP WITHOUT TIME ZONE,
    bid_opening_at TIMESTAMP WITHOUT TIME ZONE,
    contract_method VARCHAR(1000),
    bid_method VARCHAR(1000),
    notice_status VARCHAR(500),
    notice_status_code VARCHAR(255),
    detail_url VARCHAR(4000),
    relevant BOOLEAN NOT NULL,
    analysis_status VARCHAR(100),
    analysis_result TEXT,
    content_hash CHAR(64) NOT NULL,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_bid_notice_source_identity
        UNIQUE (source_code, source_notice_id, revision_key),
    CONSTRAINT ck_bid_notice_seen_order CHECK (last_seen_at >= first_seen_at)
);
CREATE INDEX ix_bid_notice_published_at ON bid_notice (published_at);
CREATE INDEX ix_bid_notice_last_seen_at ON bid_notice (last_seen_at);

CREATE TABLE bid_notice_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid_notice_id BIGINT NOT NULL,
    notice_number VARCHAR(255),
    title VARCHAR(2000) NOT NULL,
    ordering_organization VARCHAR(1000),
    published_at TIMESTAMP WITHOUT TIME ZONE,
    submission_deadline_at TIMESTAMP WITHOUT TIME ZONE,
    bid_opening_at TIMESTAMP WITHOUT TIME ZONE,
    contract_method VARCHAR(1000),
    bid_method VARCHAR(1000),
    notice_status VARCHAR(500),
    notice_status_code VARCHAR(255),
    detail_url VARCHAR(4000),
    relevant BOOLEAN NOT NULL,
    analysis_status VARCHAR(100),
    analysis_result TEXT,
    content_hash CHAR(64) NOT NULL,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_bid_notice_version_notice
        FOREIGN KEY (bid_notice_id) REFERENCES bid_notice (id) ON DELETE CASCADE,
    CONSTRAINT uk_bid_notice_version_hash UNIQUE (bid_notice_id, content_hash)
);

CREATE TABLE bid_collection_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(50) NOT NULL,
    trigger_type VARCHAR(20) NOT NULL,
    query_start_date DATE NOT NULL,
    query_end_date DATE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL,
    api_call_count INTEGER,
    collected_count INTEGER NOT NULL DEFAULT 0,
    new_count INTEGER NOT NULL DEFAULT 0,
    changed_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    error_code VARCHAR(100),
    CONSTRAINT ck_bid_collection_run_trigger
        CHECK (trigger_type IN ('AUTOMATIC', 'MANUAL', 'SCHEDULED')),
    CONSTRAINT ck_bid_collection_run_status
        CHECK (status IN ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED')),
    CONSTRAINT ck_bid_collection_run_query_range CHECK (query_end_date >= query_start_date),
    CONSTRAINT ck_bid_collection_run_time_order
        CHECK (finished_at IS NULL OR finished_at >= started_at),
    CONSTRAINT ck_bid_collection_run_counts
        CHECK ((api_call_count IS NULL OR api_call_count >= 0)
            AND collected_count >= 0 AND new_count >= 0
            AND changed_count >= 0 AND failure_count >= 0)
);
CREATE INDEX ix_bid_collection_run_source_started
    ON bid_collection_run (source_code, started_at);

CREATE TABLE bid_collection_lock (
    source_code VARCHAR(50) NOT NULL,
    query_start_date DATE NOT NULL,
    query_end_date DATE NOT NULL,
    owner_token VARCHAR(36) NOT NULL,
    acquired_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    run_id BIGINT,
    CONSTRAINT pk_bid_collection_lock
        PRIMARY KEY (source_code, query_start_date, query_end_date),
    CONSTRAINT uk_bid_collection_lock_owner UNIQUE (owner_token),
    CONSTRAINT uk_bid_collection_lock_run UNIQUE (run_id),
    CONSTRAINT fk_bid_collection_lock_run FOREIGN KEY (run_id) REFERENCES bid_collection_run (id),
    CONSTRAINT ck_bid_collection_lock_range CHECK (query_end_date >= query_start_date),
    CONSTRAINT ck_bid_collection_lock_lease CHECK (lease_expires_at > acquired_at)
);

CREATE TABLE bid_source_state (
    source_code VARCHAR(50) PRIMARY KEY,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    last_success_at TIMESTAMP WITH TIME ZONE,
    last_failure_at TIMESTAMP WITH TIME ZONE,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    next_run_at TIMESTAMP WITH TIME ZONE,
    daily_limit INTEGER,
    used_calls INTEGER NOT NULL DEFAULT 0,
    quota_date DATE,
    cooldown_until TIMESTAMP WITH TIME ZONE,
    cooldown_seconds BIGINT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(100),
    CONSTRAINT ck_bid_source_state_failures CHECK (consecutive_failures >= 0),
    CONSTRAINT ck_bid_source_state_quota
        CHECK ((daily_limit IS NULL OR daily_limit >= 0) AND used_calls >= 0),
    CONSTRAINT ck_bid_source_state_cooldown CHECK (cooldown_seconds >= 0)
);
INSERT INTO bid_source_state
    (source_code, consecutive_failures, daily_limit, used_calls, cooldown_seconds)
VALUES ('D2B', 0, 100, 0, 0)
ON CONFLICT (source_code) DO NOTHING;

CREATE TABLE bid_source_registration (
    source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(200) NOT NULL,
    site_url VARCHAR(2048) NOT NULL,
    site_url_sha256 BYTEA GENERATED ALWAYS AS (digest(site_url, 'sha256')) STORED,
    source_code VARCHAR(100),
    registration_status VARCHAR(30) NOT NULL,
    collection_method VARCHAR(30) NOT NULL,
    execution_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    check_status VARCHAR(20) NOT NULL DEFAULT 'NOT_CHECKED',
    detected_collection_method VARCHAR(30) NOT NULL DEFAULT 'UNDETERMINED',
    http_status INTEGER,
    content_type VARCHAR(255),
    check_attempt_id VARCHAR(36),
    check_started_at TIMESTAMP WITH TIME ZONE,
    checked_at TIMESTAMP WITH TIME ZONE,
    safe_failure_code VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_bid_source_registration_url_hash UNIQUE (site_url_sha256),
    CONSTRAINT ck_bid_source_registration_status
        CHECK (registration_status IN ('PENDING_REVIEW', 'UNDER_REVIEW', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_bid_source_registration_method
        CHECK (collection_method IN ('UNDETERMINED', 'OFFICIAL_API', 'PUBLIC_PAGE', 'RSS')),
    CONSTRAINT ck_bid_source_registration_execution CHECK (
        execution_enabled = FALSE OR (
            registration_status = 'APPROVED'
            AND source_code IS NOT NULL
            AND collection_method <> 'UNDETERMINED'
        )
    ),
    CONSTRAINT ck_bid_source_registration_time CHECK (updated_at >= created_at),
    CONSTRAINT ck_bid_source_registration_check_status
        CHECK (check_status IN ('NOT_CHECKED', 'CHECKING', 'REACHABLE', 'UNREACHABLE', 'BLOCKED')),
    CONSTRAINT ck_bid_source_registration_detected_method
        CHECK (detected_collection_method IN ('UNDETERMINED', 'OFFICIAL_API', 'PUBLIC_PAGE', 'RSS')),
    CONSTRAINT ck_bid_source_registration_http_status
        CHECK (http_status IS NULL OR (http_status >= 100 AND http_status <= 599)),
    CONSTRAINT ck_bid_source_registration_binding
        CHECK (source_code IS NULL OR registration_status = 'APPROVED'),
    CONSTRAINT ck_bid_source_registration_check_time CHECK (
        (check_status = 'NOT_CHECKED' AND check_attempt_id IS NULL
            AND check_started_at IS NULL AND checked_at IS NULL)
        OR (check_status = 'CHECKING' AND check_attempt_id IS NOT NULL
            AND check_started_at IS NOT NULL AND checked_at IS NULL)
        OR (check_status IN ('REACHABLE', 'UNREACHABLE', 'BLOCKED')
            AND check_attempt_id IS NULL AND check_started_at IS NULL AND checked_at IS NOT NULL)
    ),
    CONSTRAINT ck_bid_source_registration_check_failure CHECK (
        (check_status = 'REACHABLE' AND safe_failure_code IS NULL)
        OR (check_status IN ('UNREACHABLE', 'BLOCKED') AND safe_failure_code IS NOT NULL)
        OR (check_status = 'NOT_CHECKED' AND safe_failure_code IS NULL)
        OR (check_status = 'CHECKING'
            AND (safe_failure_code IS NULL OR safe_failure_code = 'CHECK_TIMEOUT'))
    ),
    CONSTRAINT ck_bid_source_registration_approved_method
        CHECK (registration_status <> 'APPROVED' OR collection_method <> 'UNDETERMINED')
);
CREATE UNIQUE INDEX uk_bid_source_registration_source_code
    ON bid_source_registration (source_code);
CREATE INDEX ix_bid_source_registration_created
    ON bid_source_registration (created_at DESC, source_id DESC);

CREATE TABLE bid_source_registration_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    action VARCHAR(40) NOT NULL,
    previous_status VARCHAR(30),
    new_status VARCHAR(30),
    previous_source_code VARCHAR(100),
    new_source_code VARCHAR(100),
    previous_execution_enabled BOOLEAN NOT NULL,
    new_execution_enabled BOOLEAN NOT NULL,
    actor VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_bid_source_registration_audit_source
        FOREIGN KEY (source_id) REFERENCES bid_source_registration (source_id),
    CONSTRAINT ck_bid_source_registration_audit_action
        CHECK (action IN ('REVIEW_STATUS_CHANGED', 'SOURCE_BOUND', 'ACTIVATED', 'DEACTIVATED'))
);
CREATE INDEX ix_bid_source_registration_audit_source_created
    ON bid_source_registration_audit (source_id, created_at);

CREATE TABLE notification_baseline (
    channel VARCHAR(50) NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    source_code VARCHAR(100) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_notification_baseline PRIMARY KEY (channel, notification_type, source_code)
);

CREATE TABLE notification_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(50) NOT NULL,
    notification_type VARCHAR(100) NOT NULL,
    source_code VARCHAR(100) NOT NULL,
    external_id VARCHAR(500) NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    content_fingerprint CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    failure_reason VARCHAR(4000),
    CONSTRAINT uk_notification_delivery_dedup
        UNIQUE (channel, notification_type, source_code, external_id, content_fingerprint),
    CONSTRAINT ck_notification_delivery_status CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);
CREATE INDEX ix_notification_delivery_status_created
    ON notification_delivery (status, created_at);

CREATE TABLE notification_subscriber (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    name VARCHAR(200),
    notification_type VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_notification_subscriber_email_type UNIQUE (email, notification_type)
);

CREATE TABLE notification_subscriber_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_delivery_id BIGINT NOT NULL,
    subscriber_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    failure_reason VARCHAR(4000),
    CONSTRAINT fk_subscriber_delivery_notification
        FOREIGN KEY (notification_delivery_id) REFERENCES notification_delivery (id),
    CONSTRAINT fk_subscriber_delivery_subscriber
        FOREIGN KEY (subscriber_id) REFERENCES notification_subscriber (id),
    CONSTRAINT uk_subscriber_delivery_event_subscriber
        UNIQUE (notification_delivery_id, subscriber_id),
    CONSTRAINT ck_notification_subscriber_delivery_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);
CREATE INDEX ix_subscriber_delivery_event_status
    ON notification_subscriber_delivery (notification_delivery_id, status);

CREATE TABLE performance_project (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    deadline DATE NOT NULL
);

CREATE TABLE performance_drive_file (
    id VARCHAR(36) PRIMARY KEY,
    origin VARCHAR(1000) NOT NULL,
    company VARCHAR(100) NOT NULL,
    drive_path VARCHAR(4000) NOT NULL,
    origin_sha256 BYTEA GENERATED ALWAYS AS (digest(origin, 'sha256')) STORED,
    company_sha256 BYTEA GENERATED ALWAYS AS (digest(company, 'sha256')) STORED,
    drive_path_sha256 BYTEA GENERATED ALWAYS AS (digest(drive_path, 'sha256')) STORED,
    filename VARCHAR(2000) NOT NULL,
    file_ext VARCHAR(100),
    file_size BIGINT NOT NULL,
    modified_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_performance_drive_locator_hash
        UNIQUE (origin_sha256, company_sha256, drive_path_sha256)
);

CREATE TABLE performance_entry (
    id VARCHAR(36) PRIMARY KEY,
    project_id VARCHAR(36) NOT NULL REFERENCES performance_project (id),
    ppt_number VARCHAR(100),
    business_name VARCHAR(1000) NOT NULL,
    business_period VARCHAR(500) NOT NULL,
    contract_amount VARCHAR(200) NOT NULL,
    client VARCHAR(500) NOT NULL,
    business_status VARCHAR(30),
    selected_file_id BIGINT,
    selected_filename VARCHAR(2000),
    selected_ext VARCHAR(100),
    evidence_type VARCHAR(30),
    kitc_status VARCHAR(30) NOT NULL,
    requested_at DATE,
    replied_at DATE,
    selected_drive_file_id VARCHAR(36) REFERENCES performance_drive_file (id),
    selected_uploaded_file_id VARCHAR(36),
    CONSTRAINT ck_performance_business_status
        CHECK (business_status IN ('COMPLETED', 'IN_PROGRESS')),
    CONSTRAINT ck_performance_evidence_type
        CHECK (evidence_type IN ('CERTIFICATE', 'CONTRACT', 'TAX_INVOICE')),
    CONSTRAINT ck_performance_kitc_status
        CHECK (kitc_status IN ('NEEDED', 'REQUESTED', 'RECEIVED')),
    CONSTRAINT ck_performance_file CHECK (
        (selected_file_id IS NULL AND selected_drive_file_id IS NULL
            AND selected_uploaded_file_id IS NULL AND selected_filename IS NULL
            AND selected_ext IS NULL AND evidence_type IS NULL)
        OR (((selected_file_id IS NOT NULL AND selected_drive_file_id IS NULL
                AND selected_uploaded_file_id IS NULL)
            OR (selected_file_id IS NULL AND selected_drive_file_id IS NOT NULL
                AND selected_uploaded_file_id IS NULL)
            OR (selected_file_id IS NULL AND selected_drive_file_id IS NULL
                AND selected_uploaded_file_id IS NOT NULL))
            AND selected_filename IS NOT NULL AND evidence_type IS NOT NULL)
    ),
    CONSTRAINT ck_performance_kitc_dates CHECK (
        (kitc_status = 'NEEDED' AND requested_at IS NULL AND replied_at IS NULL)
        OR (kitc_status = 'REQUESTED' AND requested_at IS NOT NULL AND replied_at IS NULL)
        OR (kitc_status = 'RECEIVED' AND requested_at IS NOT NULL
            AND replied_at >= requested_at AND replied_at IS NOT NULL)
    )
);

CREATE TABLE performance_uploaded_file (
    id VARCHAR(36) PRIMARY KEY,
    project_id VARCHAR(36) NOT NULL REFERENCES performance_project (id),
    entry_id VARCHAR(36) NOT NULL REFERENCES performance_entry (id),
    original_filename VARCHAR(2000) NOT NULL,
    file_ext VARCHAR(100),
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE performance_entry
    ADD CONSTRAINT fk_performance_entry_uploaded_file
    FOREIGN KEY (selected_uploaded_file_id) REFERENCES performance_uploaded_file (id);

CREATE TABLE performance_additional_evidence (
    entry_id VARCHAR(36) PRIMARY KEY REFERENCES performance_entry (id),
    selected_file_id BIGINT,
    selected_drive_file_id VARCHAR(36) REFERENCES performance_drive_file (id),
    selected_uploaded_file_id VARCHAR(36) REFERENCES performance_uploaded_file (id),
    evidence_type VARCHAR(30) NOT NULL
        CHECK (evidence_type IN ('CERTIFICATE', 'CONTRACT', 'TAX_INVOICE')),
    filename VARCHAR(2000) NOT NULL,
    ext VARCHAR(100),
    CONSTRAINT ck_performance_additional_evidence_source CHECK (
        (CASE WHEN selected_file_id IS NULL THEN 0 ELSE 1 END
        + CASE WHEN selected_drive_file_id IS NULL THEN 0 ELSE 1 END
        + CASE WHEN selected_uploaded_file_id IS NULL THEN 0 ELSE 1 END) = 1
    )
);

CREATE TABLE drive_file_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(1000) NOT NULL,
    company VARCHAR(100) NOT NULL,
    root VARCHAR(4000) NOT NULL,
    name VARCHAR(2000) NOT NULL,
    path VARCHAR(4000) NOT NULL,
    source_sha256 BYTEA GENERATED ALWAYS AS (digest(source, 'sha256')) STORED,
    company_sha256 BYTEA GENERATED ALWAYS AS (digest(company, 'sha256')) STORED,
    root_sha256 BYTEA GENERATED ALWAYS AS (digest(root, 'sha256')) STORED,
    path_sha256 BYTEA GENERATED ALWAYS AS (digest(path, 'sha256')) STORED,
    ext VARCHAR(100),
    size BIGINT NOT NULL,
    last_modified TIMESTAMP WITH TIME ZONE,
    indexed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_drive_index_locator_hash
        UNIQUE (source_sha256, company_sha256, root_sha256, path_sha256)
);

CREATE TABLE drive_index_root_state (
    source VARCHAR(1000) NOT NULL,
    company VARCHAR(100) NOT NULL,
    root VARCHAR(4000) NOT NULL,
    source_sha256 BYTEA GENERATED ALWAYS AS (digest(source, 'sha256')) STORED,
    company_sha256 BYTEA GENERATED ALWAYS AS (digest(company, 'sha256')) STORED,
    root_sha256 BYTEA GENERATED ALWAYS AS (digest(root, 'sha256')) STORED,
    status VARCHAR(20) NOT NULL CHECK (status IN ('REFRESHING', 'SUCCESS', 'FAILED')),
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    last_success_at TIMESTAMP WITH TIME ZONE,
    folder_count BIGINT NOT NULL DEFAULT 0,
    file_count BIGINT NOT NULL DEFAULT 0,
    error_code VARCHAR(100),
    CONSTRAINT pk_drive_index_root_state_hash
        PRIMARY KEY (source_sha256, company_sha256, root_sha256)
);

CREATE TABLE submission_uploaded_file (
    id VARCHAR(36) PRIMARY KEY,
    original_filename VARCHAR(2000) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE submission_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT,
    project_public_id VARCHAR(36),
    project_code VARCHAR(255),
    internal_biz_no VARCHAR(255),
    project_name VARCHAR(2000) NOT NULL,
    organization_name VARCHAR(2000),
    bid_notice_no VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    performance_project_id VARCHAR(36) REFERENCES performance_project (id),
    performance_link_initialized BOOLEAN NOT NULL DEFAULT FALSE,
    deadline DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_submission_case_project UNIQUE (project_id),
    CONSTRAINT ck_submission_case_status CHECK (status IN ('DRAFT'))
);

CREATE TABLE submission_document_requirement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_case_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    document_name VARCHAR(2000) NOT NULL,
    required BOOLEAN NOT NULL,
    evidence_text TEXT,
    source_type VARCHAR(50) NOT NULL,
    source_reference VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_submission_requirement_case
        FOREIGN KEY (submission_case_id) REFERENCES submission_case (id) ON DELETE CASCADE
);
CREATE INDEX ix_submission_requirement_case
    ON submission_document_requirement (submission_case_id, id);

CREATE TABLE submission_document_selection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_case_id BIGINT NOT NULL,
    requirement_id BIGINT NOT NULL,
    file_id BIGINT,
    file_public_id VARCHAR(36),
    uploaded_file_id VARCHAR(36) REFERENCES submission_uploaded_file (id),
    original_filename VARCHAR(2000) NOT NULL,
    file_ext VARCHAR(100),
    file_modified_at TIMESTAMP WITH TIME ZONE,
    file_updated_at TIMESTAMP WITH TIME ZONE,
    selected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_submission_selection_case
        FOREIGN KEY (submission_case_id) REFERENCES submission_case (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_selection_requirement
        FOREIGN KEY (requirement_id) REFERENCES submission_document_requirement (id) ON DELETE CASCADE,
    CONSTRAINT uk_submission_selection_requirement_file UNIQUE (requirement_id, file_id),
    CONSTRAINT ck_submission_selection_source CHECK (
        (uploaded_file_id IS NOT NULL AND file_id IS NULL AND file_public_id IS NULL)
        OR (uploaded_file_id IS NULL AND file_id IS NOT NULL AND file_public_id IS NOT NULL)
    )
);
CREATE INDEX ix_submission_selection_case
    ON submission_document_selection (submission_case_id, requirement_id);

CREATE TABLE submission_common_document (
    document_type VARCHAR(100) PRIMARY KEY,
    display_name VARCHAR(500) NOT NULL,
    file_id BIGINT,
    file_public_id VARCHAR(36),
    uploaded_file_id VARCHAR(36) REFERENCES submission_uploaded_file (id),
    original_filename VARCHAR(2000),
    file_ext VARCHAR(100),
    issued_at DATE,
    expires_at DATE,
    refresh_policy VARCHAR(30) NOT NULL,
    refresh_interval_months INTEGER,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_common_document_refresh_policy
        CHECK (refresh_policy IN ('NONE', 'EXPIRATION_BASED', 'PERIODIC')),
    CONSTRAINT ck_common_document_periodic_interval CHECK (
        (refresh_policy = 'PERIODIC' AND refresh_interval_months > 0)
        OR (refresh_policy <> 'PERIODIC' AND refresh_interval_months IS NULL)
    ),
    CONSTRAINT ck_common_document_current_reference CHECK (
        (uploaded_file_id IS NOT NULL AND file_id IS NULL
            AND file_public_id IS NULL AND original_filename IS NOT NULL)
        OR (uploaded_file_id IS NULL
            AND ((file_id IS NULL AND file_public_id IS NULL AND original_filename IS NULL)
                OR (file_id IS NOT NULL AND file_public_id IS NOT NULL
                    AND original_filename IS NOT NULL)))
    )
);

INSERT INTO submission_common_document
    (document_type, display_name, refresh_policy, refresh_interval_months, active, created_at, updated_at)
VALUES
    ('BUSINESS_REGISTRATION', '사업자등록증', 'NONE', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BID_PARTICIPATION_REGISTRATION', '경쟁입찰참가자격등록증', 'NONE', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CORPORATE_REGISTRY', '법인등기사항전부증명서', 'NONE', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CORPORATE_SEAL_CERTIFICATE', '법인인감증명서', 'PERIODIC', 3, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('PIA_INSTITUTION_CERTIFICATE', '개인정보 영향평가 기관 인증서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('AUDIT_CORPORATION_REGISTRATION', '감리법인등록증', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SMALL_BUSINESS_CERTIFICATE', '중소기업확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('WOMEN_OWNED_BUSINESS_CERTIFICATE', '여성기업확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('STARTUP_BUSINESS_CERTIFICATE', '창업기업확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CREDIT_RATING_CERTIFICATE', '신용평가등급확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('SOFTWARE_BUSINESS_STATUS_CERTIFICATE', '소프트웨어사업자 일반현황 관리확인서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('DIRECT_PRODUCTION_CERTIFICATE', '직접생산확인증명서', 'EXPIRATION_BASED', NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (document_type) DO NOTHING;

CREATE TABLE submission_document_master (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(32) NOT NULL
        CHECK (category IN ('COMPANY_COMMON', 'PERSONNEL', 'PERFORMANCE', 'OTHER')),
    requirement_category VARCHAR(32) NOT NULL,
    source_reference VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1000,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO submission_document_master
    (id, name, category, requirement_category, source_reference, sort_order)
VALUES
    ('BUSINESS_REGISTRATION', '사업자등록증', 'COMPANY_COMMON', 'COMPANY_GENERAL', 'BUSINESS_REGISTRATION', 0),
    ('BID_PARTICIPATION_REGISTRATION', '경쟁입찰참가자격등록증', 'COMPANY_COMMON', 'COMPANY_GENERAL', 'BID_PARTICIPATION_REGISTRATION', 1),
    ('CORPORATE_REGISTRY', '법인등기사항전부증명서', 'COMPANY_COMMON', 'COMPANY_GENERAL', 'CORPORATE_REGISTRY', 2),
    ('CORPORATE_SEAL_CERTIFICATE', '법인인감증명서', 'COMPANY_COMMON', 'COMPANY_GENERAL', 'CORPORATE_SEAL_CERTIFICATE', 3),
    ('PIA_INSTITUTION_CERTIFICATE', '개인정보 영향평가 기관 인증서', 'COMPANY_COMMON', 'CERTIFICATION_LICENSE', 'PIA_INSTITUTION_CERTIFICATE', 4),
    ('AUDIT_CORPORATION_REGISTRATION', '감리법인등록증', 'COMPANY_COMMON', 'CERTIFICATION_LICENSE', 'AUDIT_CORPORATION_REGISTRATION', 5),
    ('SMALL_BUSINESS_CERTIFICATE', '중소기업확인서', 'COMPANY_COMMON', 'CERTIFICATION_LICENSE', 'SMALL_BUSINESS_CERTIFICATE', 6),
    ('WOMEN_OWNED_BUSINESS_CERTIFICATE', '여성기업확인서', 'COMPANY_COMMON', 'CERTIFICATION_LICENSE', 'WOMEN_OWNED_BUSINESS_CERTIFICATE', 7),
    ('STARTUP_BUSINESS_CERTIFICATE', '창업기업확인서', 'COMPANY_COMMON', 'CERTIFICATION_LICENSE', 'STARTUP_BUSINESS_CERTIFICATE', 8),
    ('CREDIT_RATING_CERTIFICATE', '신용평가등급확인서', 'COMPANY_COMMON', 'FINANCIAL', 'CREDIT_RATING_CERTIFICATE', 9),
    ('SOFTWARE_BUSINESS_STATUS_CERTIFICATE', '소프트웨어사업자 일반현황 관리확인서', 'COMPANY_COMMON', 'CERTIFICATION_LICENSE', 'SOFTWARE_BUSINESS_STATUS_CERTIFICATE', 10),
    ('DIRECT_PRODUCTION_CERTIFICATE', '직접생산확인증명서', 'COMPANY_COMMON', 'CERTIFICATION_LICENSE', 'DIRECT_PRODUCTION_CERTIFICATE', 11),
    ('EMPLOYMENT', '재직증명서', 'PERSONNEL', 'PERSONNEL', 'EMPLOYMENT', 12),
    ('QUALIFICATION', '자격증', 'PERSONNEL', 'CERTIFICATION_LICENSE', 'QUALIFICATION', 13),
    ('KOSA_CAREER', 'KOSA 경력증명서', 'PERSONNEL', 'PERSONNEL', 'KOSA_CAREER', 14),
    ('GRADUATION', '졸업증명서', 'PERSONNEL', 'PERSONNEL', 'GRADUATION', 15),
    ('PERFORMANCE', '실적증명서', 'PERFORMANCE', 'PERFORMANCE', 'PERFORMANCE', 16)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE submission_person (
    id VARCHAR(36) PRIMARY KEY,
    submission_case_id BIGINT NOT NULL REFERENCES submission_case (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE submission_person_document (
    person_id VARCHAR(36) NOT NULL REFERENCES submission_person (id) ON DELETE CASCADE,
    document_type VARCHAR(30) NOT NULL,
    needed BOOLEAN NOT NULL DEFAULT FALSE,
    drive_file_id VARCHAR(36) REFERENCES performance_drive_file (id),
    uploaded_file_id VARCHAR(36) REFERENCES submission_uploaded_file (id),
    filename VARCHAR(2000),
    CONSTRAINT pk_submission_person_document PRIMARY KEY (person_id, document_type),
    CONSTRAINT ck_submission_person_document_source
        CHECK (drive_file_id IS NULL OR uploaded_file_id IS NULL)
);
