ALTER TABLE bid_source_discovery_result
    ADD COLUMN identifier_mapping VARCHAR(2000),
    ADD COLUMN title_mapping VARCHAR(2000),
    ADD COLUMN agency_mapping VARCHAR(2000),
    ADD COLUMN published_date_mapping VARCHAR(2000),
    ADD COLUMN deadline_mapping VARCHAR(2000),
    ADD COLUMN status_mapping VARCHAR(2000),
    ADD COLUMN attachment_mapping VARCHAR(2000),
    ADD COLUMN pagination_mapping VARCHAR(2000);

CREATE TABLE bid_source_discovery_review (
    source_id BIGINT PRIMARY KEY,
    review_status VARCHAR(30) NOT NULL,
    list_page_url VARCHAR(4000) NOT NULL,
    detail_url_pattern VARCHAR(4000) NOT NULL,
    identifier_mapping VARCHAR(2000) NOT NULL,
    title_mapping VARCHAR(2000) NOT NULL,
    agency_mapping VARCHAR(2000) NOT NULL,
    published_date_mapping VARCHAR(2000) NOT NULL,
    deadline_mapping VARCHAR(2000) NOT NULL,
    status_mapping VARCHAR(2000) NOT NULL,
    attachment_mapping VARCHAR(2000) NOT NULL,
    pagination_mapping VARCHAR(2000) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_bid_source_discovery_review_registration
        FOREIGN KEY (source_id) REFERENCES bid_source_registration (source_id) ON DELETE CASCADE,
    CONSTRAINT ck_bid_source_discovery_review_status
        CHECK (review_status IN ('PENDING_REVIEW', 'APPROVED', 'REJECTED'))
);

CREATE TABLE bid_source_discovery_review_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    previous_status VARCHAR(30) NOT NULL,
    new_status VARCHAR(30) NOT NULL,
    actor VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_bid_source_discovery_review_audit_source
        FOREIGN KEY (source_id) REFERENCES bid_source_registration (source_id),
    CONSTRAINT ck_bid_source_discovery_review_audit_action
        CHECK (action IN ('REVIEW_UPDATED', 'APPROVED', 'REJECTED'))
);

CREATE INDEX ix_bid_source_discovery_review_audit_source_created
    ON bid_source_discovery_review_audit (source_id, created_at);
