package com.comhu.bidmonitor.submission.domain;

/** Biz Assist가 현재 사용본과 갱신 상태를 관리하는 표준 공통 제출서류 유형이다. */
public enum CommonDocumentType {
    BUSINESS_REGISTRATION,
    BID_PARTICIPATION_REGISTRATION,
    CORPORATE_REGISTRY,
    CORPORATE_SEAL_CERTIFICATE,
    PIA_INSTITUTION_CERTIFICATE,
    AUDIT_CORPORATION_REGISTRATION,
    SMALL_BUSINESS_CERTIFICATE,
    WOMEN_OWNED_BUSINESS_CERTIFICATE,
    STARTUP_BUSINESS_CERTIFICATE,
    CREDIT_RATING_CERTIFICATE,
    SOFTWARE_BUSINESS_STATUS_CERTIFICATE,
    DIRECT_PRODUCTION_CERTIFICATE
}
