package com.comhu.bidmonitor.persistence;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgresqlFlywayBaselineTests {

    private static final Path BASELINE = Path.of(
            "src/main/resources/db/migration/postgresql/V1__baseline.sql"
    );

    @Test
    void baselineContainsTheCompleteCurrentSchemaWithoutH2UpgradeHistory() throws IOException {
        String sql = Files.readString(BASELINE);
        Set<String> tables = tableNames(sql);

        assertEquals(Set.of(
                "external_notice", "external_notice_attachment",
                "bid_notice", "bid_notice_version", "bid_collection_run", "bid_collection_lock",
                "bid_source_state", "bid_source_registration", "bid_source_registration_audit",
                "notification_baseline", "notification_delivery", "notification_subscriber",
                "notification_subscriber_delivery", "performance_project", "performance_entry",
                "performance_drive_file", "performance_uploaded_file", "performance_additional_evidence",
                "drive_file_index", "drive_index_root_state", "submission_case",
                "submission_document_requirement", "submission_document_selection",
                "submission_common_document", "submission_document_master", "submission_uploaded_file",
                "submission_person", "submission_person_document"
        ), tables);
        assertFalse(sql.contains("CLOB"));
        assertFalse(sql.contains("convert_to("));
        assertFalse(sql.contains("CREATE TABLE IF NOT EXISTS"));
        assertFalse(sql.contains("DROP CONSTRAINT"));
        assertFalse(Pattern.compile("(?m)^UPDATE\\s").matcher(sql).find());
        assertEquals(1, occurrences(sql, "ALTER TABLE"));
        assertTrue(sql.contains("CREATE EXTENSION IF NOT EXISTS pgcrypto"));
    }

    @Test
    void baselineUsesPostgresqlTypesAndPreservesCoreConstraints() throws IOException {
        String sql = Files.readString(BASELINE);

        assertTrue(sql.contains("published_at TIMESTAMP WITHOUT TIME ZONE"));
        assertTrue(sql.contains("first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL"));
        assertTrue(sql.contains("query_start_date DATE NOT NULL"));
        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assertTrue(sql.contains("uk_bid_notice_source_identity"));
        assertTrue(sql.contains("uk_bid_notice_version_hash"));
        assertTrue(sql.contains("pk_bid_collection_lock"));
        assertTrue(sql.contains("fk_bid_source_registration_audit_source"));
        assertTrue(sql.contains("ck_performance_file"));
        assertTrue(sql.contains("ck_submission_selection_source"));
    }

    @Test
    void oversizedNaturalKeysUseGeneratedSha256KeysWithoutRemovingSourceValues() throws IOException {
        String sql = Files.readString(BASELINE);

        assertTrue(sql.contains("site_url VARCHAR(2048) NOT NULL"));
        assertTrue(sql.contains("site_url_sha256 BYTEA GENERATED ALWAYS AS"));
        assertTrue(sql.contains("digest(site_url, 'sha256')"));
        assertTrue(sql.contains("drive_path VARCHAR(4000) NOT NULL"));
        assertTrue(sql.contains("drive_path_sha256 BYTEA GENERATED ALWAYS AS"));
        assertTrue(sql.contains("path VARCHAR(4000) NOT NULL"));
        assertTrue(sql.contains("path_sha256 BYTEA GENERATED ALWAYS AS"));
        assertTrue(sql.contains("pk_drive_index_root_state_hash"));
    }

    @Test
    void profilesKeepH2InitializationSeparateFromPostgresqlFlyway() throws IOException {
        String common = Files.readString(Path.of("src/main/resources/application.properties"));
        String h2 = Files.readString(Path.of("src/main/resources/application-h2.properties"));
        String postgres = Files.readString(Path.of("src/main/resources/application-postgres.properties"));

        assertTrue(common.contains("spring.profiles.default=h2"));
        assertTrue(h2.contains("jdbc:h2:file:./data/bid-monitor"));
        assertTrue(h2.contains("spring.sql.init.mode=always"));
        assertTrue(h2.contains("spring.flyway.enabled=false"));
        assertTrue(postgres.contains("spring.sql.init.mode=never"));
        assertTrue(postgres.contains("spring.flyway.enabled=true"));
        assertTrue(postgres.contains("classpath:db/migration/postgresql"));
        assertTrue(postgres.contains("${DB_PASSWORD}"));
        assertFalse(postgres.matches("(?s).*spring\\.datasource\\.password=[^$\\r\\n].*"));
        assertTrue(postgres.contains("SET TIME ZONE 'UTC'"));
    }

    private Set<String> tableNames(String sql) {
        Matcher matcher = Pattern.compile("(?m)^CREATE TABLE ([a-z_]+) ").matcher(sql);
        java.util.HashSet<String> names = new java.util.HashSet<>();
        while (matcher.find()) {
            names.add(matcher.group(1));
        }
        return names;
    }

    private int occurrences(String value, String token) {
        return (value.length() - value.replace(token, "").length()) / token.length();
    }
}
