package com.comhu.bidmonitor.persistence;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgresqlFlywayBaselineTests {

    private static final Path BASELINE = Path.of(
            "src/main/resources/db/migration/postgresql/V1__baseline.sql"
    );

    @Test
    void baselineContainsTheCompleteCurrentSchemaWithoutH2UpgradeHistory() throws IOException {
        String sql = Files.readString(BASELINE);
        Set<String> tables = tableNames(sql);

        assertEquals(Set.of(
                "external_notice", "external_notice_attachment",
                "bid_notice", "bid_notice_version", "bid_collection_run", "bid_collection_lock",
                "bid_source_state", "bid_source_registration", "bid_source_registration_audit",
                "notification_baseline", "notification_delivery", "notification_subscriber",
                "notification_subscriber_delivery", "performance_project", "performance_entry",
                "performance_drive_file", "performance_uploaded_file", "performance_additional_evidence",
                "drive_file_index", "drive_index_root_state", "submission_case",
                "submission_document_requirement", "submission_document_selection",
                "submission_common_document", "submission_document_master", "submission_uploaded_file",
                "submission_person", "submission_person_document"
        ), tables);
        assertFalse(sql.contains("CLOB"));
        assertFalse(sql.contains("convert_to("));
        assertFalse(sql.contains("CREATE TABLE IF NOT EXISTS"));
        assertFalse(sql.contains("DROP CONSTRAINT"));
        assertFalse(Pattern.compile("(?m)^UPDATE\\s").matcher(sql).find());
        assertEquals(1, occurrences(sql, "ALTER TABLE"));
        assertTrue(sql.contains("CREATE EXTENSION IF NOT EXISTS pgcrypto"));
    }

    @Test
    void baselineUsesPostgresqlTypesAndPreservesCoreConstraints() throws IOException {
        String sql = Files.readString(BASELINE);

        assertTrue(sql.contains("published_at TIMESTAMP WITHOUT TIME ZONE"));
        assertTrue(sql.contains("first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL"));
        assertTrue(sql.contains("query_start_date DATE NOT NULL"));
        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assertTrue(sql.contains("uk_bid_notice_source_identity"));
        assertTrue(sql.contains("uk_bid_notice_version_hash"));
        assertTrue(sql.contains("pk_bid_collection_lock"));
        assertTrue(sql.contains("fk_bid_source_registration_audit_source"));
        assertTrue(sql.contains("ck_performance_file"));
        assertTrue(sql.contains("ck_submission_selection_source"));
    }

    @Test
    void oversizedNaturalKeysUseGeneratedSha256KeysWithoutRemovingSourceValues() throws IOException {
        String sql = Files.readString(BASELINE);

        assertTrue(sql.contains("site_url VARCHAR(2048) NOT NULL"));
        assertTrue(sql.contains("site_url_sha256 BYTEA GENERATED ALWAYS AS"));
        assertTrue(sql.contains("digest(site_url, 'sha256')"));
        assertTrue(sql.contains("drive_path VARCHAR(4000) NOT NULL"));
        assertTrue(sql.contains("drive_path_sha256 BYTEA GENERATED ALWAYS AS"));
        assertTrue(sql.contains("path VARCHAR(4000) NOT NULL"));
        assertTrue(sql.contains("path_sha256 BYTEA GENERATED ALWAYS AS"));
        assertTrue(sql.contains("pk_drive_index_root_state_hash"));
    }

    @Test
    void profilesKeepH2InitializationSeparateFromPostgresqlFlyway() throws IOException {
        String common = Files.readString(Path.of("src/main/resources/application.properties"));
        String h2 = Files.readString(Path.of("src/main/resources/application-h2.properties"));
        String postgres = Files.readString(Path.of("src/main/resources/application-postgres.properties"));

        assertTrue(common.contains("spring.profiles.default=h2"));
        assertTrue(h2.contains("jdbc:h2:file:./data/bid-monitor"));
        assertTrue(h2.contains("spring.sql.init.mode=always"));
        assertTrue(h2.contains("spring.flyway.enabled=false"));
        assertTrue(postgres.contains("spring.sql.init.mode=never"));
        assertTrue(postgres.contains("spring.flyway.enabled=true"));
        assertTrue(postgres.contains("classpath:db/migration/postgresql"));
        assertTrue(postgres.contains("${DB_PASSWORD}"));
        assertFalse(postgres.matches("(?s).*spring\\.datasource\\.password=[^$\\r\\n].*"));
        assertTrue(postgres.contains("SET TIME ZONE 'UTC'"));
    }

    @Test
    void composePinsSupportedPostgresqlAndRequiresASecret() throws IOException {
        String compose = Files.readString(Path.of("compose.yaml"));
        String example = Files.readString(Path.of(".env.example"));

        assertTrue(compose.contains("image: postgres:16.15-bookworm"));
        assertTrue(compose.contains("POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?"));
        assertTrue(compose.contains("bid-monitor-postgres-data:/var/lib/postgresql/data"));
        assertTrue(compose.contains("pg_isready"));
        assertTrue(example.contains("POSTGRES_PASSWORD="));
        assertTrue(example.contains("DB_PASSWORD="));
        assertFalse(Pattern.compile("(?m)^[A-Z_]*PASSWORD=.+$").matcher(example).find());
    }

    @Test
    void discoveryMigrationStoresOnlyBoundedMetadata() throws IOException {
        String sql = Files.readString(Path.of(
                "src/main/resources/db/migration/postgresql/V2__bid_source_discovery.sql"));

        assertTrue(sql.contains("CREATE TABLE bid_source_discovery_result"));
        assertTrue(sql.contains("REFERENCES bid_source_registration (source_id) ON DELETE CASCADE"));
        assertTrue(sql.contains("analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL"));
        assertTrue(sql.contains("detail_url_pattern VARCHAR(4000)"));
        assertTrue(sql.contains("reason_codes VARCHAR(2000) NOT NULL"));
        assertFalse(sql.toLowerCase().contains("html"));
        assertFalse(sql.toLowerCase().contains("response_body"));
    }

    @Test
    @EnabledIfEnvironmentVariable(named = "BIZ_ASSIST_POSTGRES_TEST_ENABLED", matches = "(?i)true")
    void migratesEmptyPostgresqlAndRoundTripsDatesTimesAndLocatorHashes() throws Exception {
        String url = "jdbc:postgresql://" + env("DB_HOST") + ":" + env("DB_PORT") + "/" + env("DB_NAME");
        String user = env("DB_USER");
        String password = env("DB_PASSWORD");

        Flyway.configure()
                .dataSource(url, user, password)
                .locations("classpath:db/migration/postgresql")
                .load()
                .migrate();

        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            assertPostgresqlSchema(connection);
            assertPostgresqlRoundTrips(connection);
        }
    }

    private void assertPostgresqlSchema(Connection connection) throws SQLException {
        assertEquals(29, queryInt(connection, """
                SELECT COUNT(*) FROM pg_tables
                WHERE schemaname = 'public' AND tablename <> 'flyway_schema_history'
                """));
        assertEquals(2, queryInt(connection, """
                SELECT COUNT(*) FROM flyway_schema_history
                WHERE version IN ('1', '2') AND success = TRUE
                """));
        assertEquals(1, queryInt(connection, "SELECT COUNT(*) FROM pg_extension WHERE extname = 'pgcrypto'"));
        assertEquals(1, queryInt(connection, "SELECT COUNT(*) FROM bid_source_state WHERE source_code = 'D2B'"));
        assertEquals(12, queryInt(connection, "SELECT COUNT(*) FROM submission_common_document"));
        assertEquals(17, queryInt(connection, "SELECT COUNT(*) FROM submission_document_master"));

        Set<String> constraints = queryStrings(connection, """
                SELECT conname FROM pg_constraint WHERE connamespace = 'public'::regnamespace
                """);
        assertTrue(constraints.containsAll(Set.of(
                "uk_bid_notice_source_identity", "uk_bid_notice_version_hash",
                "pk_bid_collection_lock", "fk_bid_source_registration_audit_source",
                "ck_performance_file", "ck_submission_selection_source",
                "uk_bid_source_registration_url_hash", "uk_performance_drive_locator_hash",
                "uk_drive_index_locator_hash", "pk_drive_index_root_state_hash"
        )));

        Set<String> indexes = queryStrings(connection, """
                SELECT indexname FROM pg_indexes WHERE schemaname = 'public'
                """);
        assertTrue(indexes.containsAll(Set.of(
                "ix_bid_notice_published_at", "ix_bid_notice_last_seen_at",
                "ix_bid_collection_run_source_started", "uk_bid_source_registration_source_code",
                "ix_bid_source_registration_audit_source_created",
                "ix_submission_requirement_case", "ix_submission_selection_case"
        )));
    }

    private void assertPostgresqlRoundTrips(Connection connection) throws SQLException {
        connection.setAutoCommit(false);
        try (Statement statement = connection.createStatement()) {
            statement.execute("SET LOCAL TIME ZONE 'UTC'");
        }
        try {
            String suffix = UUID.randomUUID().toString();
            LocalDate date = LocalDate.of(2026, 9, 30);
            LocalDateTime localDateTime = LocalDateTime.of(2026, 9, 30, 12, 34, 56, 123_456_000);
            Instant instant = Instant.parse("2026-09-30T03:34:56.123456Z");
            OffsetDateTime utc = instant.atOffset(ZoneOffset.UTC);

            try (PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO bid_notice (
                        source_code, source_notice_id, revision_key, title, published_at,
                        relevant, content_hash, first_seen_at, last_seen_at
                    ) VALUES (?, ?, '', ?, ?, TRUE, ?, ?, ?)
                    """)) {
                statement.setString(1, "PG_TEST");
                statement.setString(2, suffix);
                statement.setString(3, "PostgreSQL timestamp fixture");
                statement.setObject(4, localDateTime);
                statement.setString(5, "a".repeat(64));
                statement.setObject(6, utc);
                statement.setObject(7, utc);
                statement.executeUpdate();
            }
            try (PreparedStatement statement = connection.prepareStatement("""
                    SELECT published_at, first_seen_at FROM bid_notice
                    WHERE source_code = 'PG_TEST' AND source_notice_id = ?
                    """)) {
                statement.setString(1, suffix);
                try (ResultSet result = statement.executeQuery()) {
                    assertTrue(result.next());
                    assertEquals(localDateTime, result.getObject("published_at", LocalDateTime.class));
                    assertEquals(instant, result.getObject("first_seen_at", OffsetDateTime.class).toInstant());
                }
            }

            String projectId = UUID.randomUUID().toString();
            try (PreparedStatement statement = connection.prepareStatement(
                    "INSERT INTO performance_project(id, name, deadline) VALUES (?, ?, ?)")) {
                statement.setString(1, projectId);
                statement.setString(2, "PostgreSQL date fixture");
                statement.setObject(3, date);
                statement.executeUpdate();
            }
            try (PreparedStatement statement = connection.prepareStatement(
                    "SELECT deadline FROM performance_project WHERE id = ?")) {
                statement.setString(1, projectId);
                try (ResultSet result = statement.executeQuery()) {
                    assertTrue(result.next());
                    assertEquals(date, result.getObject("deadline", LocalDate.class));
                }
            }

            try (PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO submission_case(project_name, status, created_at, updated_at)
                    VALUES (?, 'DRAFT', ?, ?)
                    """)) {
                statement.setString(1, "PostgreSQL submission fixture");
                statement.setObject(2, utc);
                statement.setObject(3, utc);
                statement.executeUpdate();
            }

            assertGeneratedHash(connection, """
                    INSERT INTO bid_source_registration (
                        source_name, site_url, registration_status, collection_method,
                        execution_enabled, check_status, detected_collection_method, created_at, updated_at
                    ) VALUES (?, ?, 'PENDING_REVIEW', 'UNDETERMINED', FALSE,
                        'NOT_CHECKED', 'UNDETERMINED', ?, ?)
                    """, "SELECT site_url, octet_length(site_url_sha256) FROM bid_source_registration WHERE site_url = ?",
                    "PostgreSQL source", "https://example.test/" + suffix, utc, utc);

            String driveId = UUID.randomUUID().toString();
            assertGeneratedHash(connection, """
                    INSERT INTO performance_drive_file (
                        id, origin, company, drive_path, filename, file_size
                    ) VALUES (?, ?, ?, ?, 'evidence.pdf', 1)
                    """, "SELECT drive_path, octet_length(drive_path_sha256) FROM performance_drive_file WHERE id = ?",
                    driveId, "fixture", "CNH", "/long/path/" + suffix, driveId);

            assertGeneratedHash(connection, """
                    INSERT INTO drive_file_index (
                        source, company, root, name, path, size, indexed_at
                    ) VALUES (?, ?, ?, 'evidence.pdf', ?, 1, ?)
                    """, "SELECT path, octet_length(path_sha256) FROM drive_file_index WHERE path = ?",
                    "fixture", "CNH", "/root/" + suffix, "/root/" + suffix + "/evidence.pdf", utc,
                    "/root/" + suffix + "/evidence.pdf");

            assertGeneratedHash(connection, """
                    INSERT INTO drive_index_root_state (
                        source, company, root, status
                    ) VALUES (?, ?, ?, 'SUCCESS')
                    """, "SELECT root, octet_length(root_sha256) FROM drive_index_root_state WHERE root = ?",
                    "fixture", "CNH", "/root-state/" + suffix, "/root-state/" + suffix);
        } finally {
            connection.rollback();
            connection.setAutoCommit(true);
        }
    }

    private void assertGeneratedHash(
            Connection connection,
            String insertSql,
            String selectSql,
            Object... parameters
    ) throws SQLException {
        int insertParameterCount = parameters.length - 1;
        try (PreparedStatement statement = connection.prepareStatement(insertSql)) {
            for (int index = 0; index < insertParameterCount; index++) {
                statement.setObject(index + 1, parameters[index]);
            }
            statement.executeUpdate();
        }
        try (PreparedStatement statement = connection.prepareStatement(selectSql)) {
            statement.setObject(1, parameters[parameters.length - 1]);
            try (ResultSet result = statement.executeQuery()) {
                assertTrue(result.next());
                assertFalse(result.getString(1).isBlank());
                assertEquals(32, result.getInt(2));
            }
        }
    }

    private int queryInt(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement(); ResultSet result = statement.executeQuery(sql)) {
            assertTrue(result.next());
            return result.getInt(1);
        }
    }

    private Set<String> queryStrings(Connection connection, String sql) throws SQLException {
        Set<String> values = new HashSet<>();
        try (Statement statement = connection.createStatement(); ResultSet result = statement.executeQuery(sql)) {
            while (result.next()) {
                values.add(result.getString(1));
            }
        }
        return values;
    }

    private String env(String name) {
        String value = System.getenv(name);
        if (value == null || value.isBlank()) {
            throw new IllegalStateException(name + " is required for PostgreSQL integration tests.");
        }
        return value;
    }

    private Set<String> tableNames(String sql) {
        Matcher matcher = Pattern.compile("(?m)^CREATE TABLE ([a-z_]+) ").matcher(sql);
        java.util.HashSet<String> names = new java.util.HashSet<>();
        while (matcher.find()) {
            names.add(matcher.group(1));
        }
        return names;
    }

    private int occurrences(String value, String token) {
        return (value.length() - value.replace(token, "").length()) / token.length();
    }
}
